name: unitconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  provider: ^6.0.5
  firebase_storage: ^11.2.6
  carousel_slider: ^5.0.0
  firebase_database: ^10.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/user.png
    - lib/assets/matematica.png
    - lib/assets/fisica.png
    - lib/assets/programacion.png
    - lib/assets/ada_lovelace.png
    - lib/assets/mark_hopper.png
    - lib/assets/margaret_hamilton.png
    - lib/assets/default_avatar.png
    - lib/assets/fondologin.jpg
    - lib/assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

